### ISSUE TITLE
Error for tasks where input and output grid size do not match

### ISSUE THREAD

**Issue by kksinghal** [khalil-research/ARGA-AAAI23#3]
Hi,
To reproduce: `python main.py 39a8645d.json training`
I get the following error for task id 39a8645d in training. I also get similar error in calculate_score function in other tasks as well, where input-output size do not match. Does this method work only for same input-output sizes? Thanks

```
Running task.solve() for #39a8645d
Initializing Frontier
Traceback (most recent call last):
  File "/Users/kartik/Desktop/ARGA-AAAI23/main.py", line 40, in <module>
    solve_task_id(task_file, task_type)
  File "/Users/kartik/Desktop/ARGA-AAAI23/main.py", line 16, in solve_task_id
    abstraction, solution_apply_call, error, train_error, solving_time, nodes_explored = task.solve(
                                                                                         ^^^^^^^^^^^
  File "/Users/kartik/Desktop/ARGA-AAAI23/task.py", line 114, in solve
    stop_search = self.initialize_frontier()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kartik/Desktop/ARGA-AAAI23/task.py", line 230, in initialize_frontier
    self.constraints_acquisition_global()
  File "/Users/kartik/Desktop/ARGA-AAAI23/task.py", line 718, in constraints_acquisition_global
    or (data["color"] == input.background_color and self.train_output[i].graph.nodes[node][
                                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/kartik/anaconda3/envs/arc/lib/python3.12/site-packages/networkx/classes/reportviews.py", line 194, in __getitem__
    return self._nodes[n]
           ~~~~~~~~~~~^^^
KeyError: (0, 3)
```

**Comment by xuwil** [comment]
Thanks for the question!
You are correct that the scope of the current implementation only includes tasks with the same input/output sizes.
